version: '3.9'

services:

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user_services:
    build: ./user_services
    container_name: user_services
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./user_services:/app
      - /app/node_modules  # prevents host from overwriting container’s node_modules
    command: nodemon index.js

  task_services:
    build: ./task_services
    container_name: task_services
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./task_services:/app
      - /app/node_modules
    command: nodemon index.js

  notification_services:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    command: nodemon index.js

volumes:
  data:
